name: CI for the Biosegura project

# Controles que se tienen en cuenta cuando el workflow corre
on:
  # Activa el workflow con un push (tambien se puede pull request) a una rama
  push:
    branches:
      - development

  #Permite que este workflow se pueda correr tambien manualmente desde github (en la seccion Actions)
  workflow_dispatch:

# Aquellas acciones que ejecutara nuestro workflow
jobs:
  # El nombre de un job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "udea-biosegura"
          heroku_email: "mateo.baena@hotmail.com"
          
      - name: Upload artifact
      - uses: actions/upload-artifact@v1
        with:
          name: failing tests report
          path: file:///home/runner/work/UdeABiosegura/UdeABiosegura/build/reports/tests/test/index.html
